- name: apt-get install
  apt: name={{ item }}
  with_items:
    - cmake
    - autoconf
    - libtool
    - gcc
    - g++
    - gdb
    - clang-3.6
    - lldb-3.6

# global
- include: global.yml

# gdb
- copy: src=.gdbinit dest={{ HOME }}/.gdbinit

# clang
# for irony-mode
- apt: name=libclang-3.6-dev
- command: ln -s /usr/bin/clang-3.6 /usr/local/bin/clang