- name: apt-get install
  apt: name={{ item }}
  with_items:
    - cmake
    - autoconf
    - libtool
    - gcc
    - gdb
    - clang-3.6
    - lldb-3.6


# gdb
- copy: src=.gdbinit dest={{ HOME }}/.gdbinit