- name: apt-get install
  apt: name={{ item }}
  with_items:
    - cmake
    - autoconf
    - libtool
    - gcc
    - g++
    - gdb
    - clang
    - lldb

# irony-mode
- apt: name=libclang-dev

# clang
- file: src=/usr/bin/clang dest=/etc/alternatives/cc state=link
- file: src=/etc/alternatives/cc dest=/usr/bin/cc state=link
- file: src=/usr/bin/clang++ dest=/etc/alternatives/c++ state=link
- file: src=/etc/alternatives/c++ dest=/usr/bin/c++ state=link

# clang-format
- apt: name=clang-format
- copy: src=.clang-format dest={{ HOME }}/.clang-format

# valgrind
- apt: name=valgrind
- copy: src=.valgrindrc dest={{ HOME }}/.valgrindrc owner={{ USER }} group={{ USER }}

# # gdb
# - apt: name=dpkg-dev
# - command: apt-get source libc6
# - copy: src=.gdbinit dest={{ HOME }}/.gdbinit
