# docker

# aufs
- shell: apt-get install -y linux-image-extra-$(uname -r)

# http://apt.dockerproject.org/repo/pool/main/d/docker-engine/docker-engine_1.8.2-0~trusty_amd64.deb
- copy: src=docker-engine_1.8.2-0~trusty_amd64.deb dest=/home/vagrant/docker-engine_1.8.2-0~trusty_amd64.deb
- command: dpkg -i docker-engine_1.8.2-0~trusty_amd64.deb
- file: path=/usr/bin/docker mode=4755

- copy: src=docker dest=/etc/default/docker
- file: path=/home/vagrant/docker owner=vagrant group=vagrant state=directory
- synchronize: src=certs/ dest=/home/vagrant/docker/certs/
- service: name=docker state=restarted
