# docker

# aufs
- shell: apt-get install -y linux-image-extra-$(uname -r)

# http://apt.dockerproject.org/repo/pool/main/d/docker-engine/docker-engine_1.9.1-0~trusty_amd64.deb
- copy: src=docker-engine_{{ DOCKER_VERSION }}-0~trusty_amd64.deb dest=/home/vagrant/docker-engine_{{ DOCKER_VERSION }}-0~trusty_amd64.deb
- command: dpkg -i docker-engine_{{ DOCKER_VERSION }}-0~trusty_amd64.deb
- file: path=/usr/bin/docker mode=4755

- copy: src=docker dest=/etc/default/docker
- file: path=/home/vagrant/docker owner=vagrant group=vagrant state=directory
- synchronize: src=certs/ dest=/home/vagrant/docker/certs/
- service: name=docker state=restarted

## registry
# docker run -it -p 5000:5000 registry:2

## docker compose
# pip install docker-compose
# docker-compose up
# docker-compose up nginx


## docker swarm
# docker run -p 2375:2375 swarm m 192.168.33.11:2376,192.168.33.12:2376
# DOCKER_HOST=192.168.33.10:2375 docker-compose up
