## emacs25
- shell: add-apt-repository -y ppa:kelleyk/emacs &&
         apt-get update &&
         apt-get install emacs25

# for zsh
- copy: src=.zshrc_emacs dest={{ HOME }}/.zshrc_emacs

# irony-install-server
- shell: mkdir -p /tmp/build-irony-server &&
         cd /tmp/build-irony-server &&
         cmake -DCMAKE_INSTALL_PREFIX={{ HOME }}/.emacs.d/irony/ {{ HOME }}/.emacs.d/elpa/irony-{{ IRONY_VERSION }}/server &&
         cmake --build . --use-stderr --config Release --target install
