# emacs
- apt: name=postfix
- command: apt-get build-dep -y emacs24
- copy: src=emacs-24.5.tar.xz dest=/home/vagrant/emacs-24.5.tar.xz
- shell: tar xvf emacs-24.5.tar.xz && cd emacs-24.5 && ./configure --prefix=/opt/app/emacs && make install
