# emacs
# http://ftp.gnu.org/gnu/emacs/emacs-24.5.tar.xz
- copy: src=emacs-24.5.tar.xz dest=/home/vagrant/emacs-24.5.tar.xz
- shell: tar xvf emacs-24.5.tar.xz &&
         cd emacs-24.5 &&
         ./configure --prefix=/opt/app/emacs &&
         make -j `nproc` &&
         make install

# irony-install-server
# cd /tmp/build-irony-server-0.2.0-cvs4 &&
# make -DCMAKE_INSTALL_PREFIX=/home/vagrant/.emacs.d/irony/ /home/vagrant/.emacs.d/elpa/irony-20151016.1420/server &&
# cmake --build . --use-stderr --config Release --target install

# rtags
- include: rtags.yml