- copy: src=sources.list dest=/etc/apt/sources.list

# Run the equivalent of "apt-get update" as a separate step
- apt: update_cache=yes

# Update all packages to the latest version
- apt: upgrade=dist

- name: apt-get install
  apt: name={{ item }}
  with_items:
    - default-jdk
    - htop
    - git
    - gcc
    - cmake
    - gdb
    - clang-3.6
    - lldb-3.6
    - silversearcher-ag
    - tshark
    - bridge-utils
    - libmysqlclient-dev
    - libgit2-dev
    - libtool
    - python-mysqldb
    - redis-server
    - unzip
