---
- hosts: all
  vars:
    DOCKER_VERSION: 1.8.3
    HOME: /home/vagrant

  sudo: true
  tasks:
    # init
    - include: init.yml

    # apt
    - include: apt.yml

    # git
    - include: git.yml

    # clang
    - include: clang.yml

    # ruby
    - include: ruby.yml

    # java
    - apt: name=default-jdk

    # python
    - include: python.yml

    # golang
    - include: go.yml

    # docker
    - include: docker.yml

    # mysql
    - include: mysql.yml
      
    # emacs
    - include: emacs.yml

    # zsh
    - include: zsh.yml

    # tmux
    - copy: src=.tmux.conf dest=/home/vagrant/.tmux.conf

    # etcd
    - include: etcd.yml

    # kubernetes
    - include: k8s.yml

    # bochs
    - include: bochs.yml

    # systemtap
    - include: systemtap.yml

    # # gui
    # - include: gui.yml
