---
- hosts: all
  sudo: true
  tasks:
    # init
    - include: init.yml

    # python
    - include: python.yml

    # golang
    - include: go.yml

    # docker
    - include: docker.yml

    # mysql
    - include: mysql.yml
      
    # emacs
    - include: emacs.yml

    # zsh
    - include: zsh.yml

    # etcd
    - include: etcd.yml

    # kubernetes
    - include: k8s.yml

    # tmux
    - copy: src=.tmux.conf dest=/home/vagrant/.tmux.conf

    # bochs
    - include: bochs.yml

    # # eclipse
    # - include: eclipse.yml
