---
- hosts: all
  vars:
    USER: ubuntu
    HOME: /home/ubuntu
    IRONY_VERSION: "20161106.830"

  become: true
  tasks:
    # init
    - include: init.yml

    # apt
    - include: apt.yml

    # zsh
    - include: zsh.yml

    # git
    - include: git.yml

    # clang
    - include: clang.yml

    # emacs
    - include: emacs.yml

    # rtags
    - include: rtags.yml
