# rtags
# git clone git@github.com:Andersbakken/rtags.git
# git submodule init
# git submodule update
- shell: rsync -avP {{ HOME }}/github/rtags/ {{ HOME }}/rtags/ &&
         cd {{ HOME }}/rtags &&
         cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DEMACS=/opt/app/emacs/bin/emacs &&
         make -j `nproc` &&
         make install

- file: src={{ HOME }}/rtags/bin/gcc-rtags-wrapper.sh dest=/usr/local/bin/cc state=link
- file: src={{ HOME }}/rtags/bin/gcc-rtags-wrapper.sh dest=/usr/local/bin/c++ state=link
- file: src={{ HOME }}/rtags/bin/gcc-rtags-wrapper.sh dest=/usr/local/bin/gcc state=link
- file: src={{ HOME }}/rtags/bin/gcc-rtags-wrapper.sh dest=/usr/local/bin/g++ state=link

# start rdm
- copy: src=rdm.conf dest=/etc/init/rdm.conf

# for zsh
- copy: src=.zshrc_rtags dest={{ HOME }}/.zshrc_rtags