# rtags
- shell: git clone git@github.com:Andersbakken/rtags.git &&
         cd {{ HOME }}/rtags &&
         git submodule init &&
         git submodule update &&
         cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=1 &&
         make -j `nproc` &&
         make install

- file: src={{ HOME }}/rtags/bin/gcc-rtags-wrapper.sh dest=/usr/local/bin/cc state=link
- file: src={{ HOME }}/rtags/bin/gcc-rtags-wrapper.sh dest=/usr/local/bin/c++ state=link
- file: src={{ HOME }}/rtags/bin/gcc-rtags-wrapper.sh dest=/usr/local/bin/gcc state=link
- file: src={{ HOME }}/rtags/bin/gcc-rtags-wrapper.sh dest=/usr/local/bin/g++ state=link

# start rdm
- copy: src=rdm.service dest=/etc/systemd/system/rdm.service
- shell: systemctl enable rdm.service &&
         systemctl start rdm.service
