# rtags
# git clone git@github.com:Andersbakken/rtags.git
- shell: rsync -avP {{ HOME }}/github/rtags/ {{ HOME }}/rtags/ && cd {{ HOME }}/rtags && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DEMACS=/opt/app/emacs/bin/emacs && make -j `nproc` && make install
