# rtags
# git clone git@github.com:Andersbakken/rtags.git
# git submodule init
# git submodule update
- shell: rsync -avP {{ HOME }}/github/rtags/ {{ HOME }}/rtags/ &&
         cd {{ HOME }}/rtags &&
         cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DEMACS=/opt/app/emacs/bin/emacs &&
         make -j `nproc` &&
         make install &&
         ln -s {{ HOME }}/rtags/bin/gcc-rtags-wrapper.sh /usr/local/bin/cc &&
         ln -s {{ HOME }}/rtags/bin/gcc-rtags-wrapper.sh /usr/local/bin/c++

# start rdm
- copy: src=rdm.conf dest=/etc/init/rdm.conf
