# ruby
- apt: name=libssl-dev
- apt: name=zlib1g-dev

# https://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.4.tar.xz
- copy: src=ruby-{{ RUBY_VERSION }}.tar.xz dest={{ HOME }}/ruby-{{ RUBY_VERSION }}.tar.xz
- shell: tar xvf ruby-{{ RUBY_VERSION }}.tar.xz &&
         cd ruby-{{ RUBY_VERSION }} &&
         ./configure --prefix=/opt/app/ruby &&
         make -j `nproc` &&
         make install

- shell: /opt/app/ruby/bin/gem sources --remove https://rubygems.org/ &&
         /opt/app/ruby/bin/gem sources --add https://ruby.taobao.org/ &&
         /opt/app/ruby/bin/gem install chef

- copy: src=.zshrc_ruby dest={{ HOME }}/.zshrc_ruby